import type { BlackCard, WhiteCard } from "./types.js";

export const blackCards: BlackCard[] = [
  { id: "black-001", text: "A nova joia rara da firma e _____ depois das duas da manhã.", pick: 1 },
  { id: "black-002", text: "O brinde oficial do inferninho VIP agora vem com _____.", pick: 1 },
  { id: "black-003", text: "Ninguém esperava que o casamento acabasse por causa de _____.", pick: 1 },
  { id: "black-004", text: "Minha bio do app de namoro só diz: _____, sem perguntas.", pick: 1 },
  { id: "black-005", text: "O RH chamou de incidente. Eu chamei de _____.", pick: 1 },
  { id: "black-006", text: "A verdadeira causa do apagão no Discord foi _____.", pick: 1 },
  { id: "black-007", text: "No cofre secreto da rainha das festas, só tinha _____.", pick: 1 },
  { id: "black-008", text: "O padre respirou fundo quando viu _____ no confessionário.", pick: 1 },
  { id: "black-009", text: "A terapia ia bem até eu admitir minha obsessão por _____.", pick: 1 },
  { id: "black-010", text: "O plano premium do caos inclui glitter, culpa e _____.", pick: 1 },
  { id: "black-011", text: "Na noite em que tudo deu errado, o primeiro sinal foi _____.", pick: 1 },
  { id: "black-012", text: "O novo reality show foi cancelado depois do episódio sobre _____.", pick: 1 },
  { id: "black-013", text: "A joia amaldiçoada só concede poder para quem trouxer _____.", pick: 1 },
  { id: "black-014", text: "Minha estratégia para conquistar a sala inteira começa com _____.", pick: 1 },
  { id: "black-015", text: "O manual de etiqueta proibiu expressamente _____.", pick: 1 },
  { id: "black-016", text: "O que realmente acontece na call quando o host sai?", pick: 1 },
  { id: "black-017", text: "A desculpa oficial foi trânsito, mas todos sabiam que era _____.", pick: 1 },
  { id: "black-018", text: "O segredo da longevidade é hidratação, protetor solar e _____.", pick: 1 },
  { id: "black-019", text: "O drink da casa se chama Diamante Sujo e leva _____.", pick: 1 },
  { id: "black-020", text: "A próxima atualização do servidor vai nerfar _____.", pick: 1 }
];

export const whiteCards: WhiteCard[] = [
  { id: "white-001", text: "um pix suspeito feito com muita convicção" },
  { id: "white-002", text: "seduzir o caos e pedir recibo" },
  { id: "white-003", text: "um áudio de sete minutos começando com 'não surta'" },
  { id: "white-004", text: "a autoestima de alguém com três taças de espumante" },
  { id: "white-005", text: "um robe aberto e nenhuma responsabilidade emocional" },
  { id: "white-006", text: "mentir no currículo e entregar performance de Oscar" },
  { id: "white-007", text: "uma joia falsa com energia de divórcio milionário" },
  { id: "white-008", text: "o grupo do WhatsApp que destrói carreiras" },
  { id: "white-009", text: "um beijo tecnicamente legal, moralmente indefensável" },
  { id: "white-010", text: "a coragem alcoólica de mandar 'saudade'" },
  { id: "white-011", text: "um coach de sensualidade com ring light" },
  { id: "white-012", text: "fazer terapia só para aprender termos novos para brigar" },
  { id: "white-013", text: "um after que deveria ser crime administrativo" },
  { id: "white-014", text: "chamar vergonha de conceito artístico" },
  { id: "white-015", text: "flertar como se o juízo fosse opcional" },
  { id: "white-016", text: "uma dívida emocional parcelada em doze vezes" },
  { id: "white-017", text: "um banho premium de perfume barato" },
  { id: "white-018", text: "a planilha secreta dos contatinhos" },
  { id: "white-019", text: "trocar maturidade por uma jaqueta bonita" },
  { id: "white-020", text: "um nude descrito como apresentação institucional" },
  { id: "white-021", text: "a elite decadente do karaokê" },
  { id: "white-022", text: "um cristal energizado com ressentimento" },
  { id: "white-023", text: "dar em cima de problema com potencial" },
  { id: "white-024", text: "um silêncio constrangedor usando salto alto" },
  { id: "white-025", text: "a ressaca moral com nota fiscal" },
  { id: "white-026", text: "um plano perfeito narrado por alguém péssimo" },
  { id: "white-027", text: "mandar indireta e chamar de literatura" },
  { id: "white-028", text: "a sensualidade fiscal de dividir a conta certinho" },
  { id: "white-029", text: "um segredo de família com Wi-Fi instável" },
  { id: "white-030", text: "rir no pior momento possível" },
  { id: "white-031", text: "um convite que claramente deveria ter sido recusado" },
  { id: "white-032", text: "um ex que reaparece como notificação do apocalipse" },
  { id: "white-033", text: "o perfume doce da má decisão" },
  { id: "white-034", text: "uma coroa de plástico e poder absoluto" },
  { id: "white-035", text: "transformar carência em networking" },
  { id: "white-036", text: "a sinceridade cruel de quem passou do limite" },
  { id: "white-037", text: "um contrato verbal assinado no banheiro da festa" },
  { id: "white-038", text: "luxo, lixo e uma playlist impecável" },
  { id: "white-039", text: "a paz espiritual de bloquear alguém" },
  { id: "white-040", text: "um hobby caro chamado autossabotagem" },
  { id: "white-041", text: "o brilho molhado da humilhação pública" },
  { id: "white-042", text: "um date que virou sindicância" },
  { id: "white-043", text: "fazer charme para a pessoa errada com excelência" },
  { id: "white-044", text: "um diamante, duas mentiras e zero arrependimento" },
  { id: "white-045", text: "a fé inabalável em mensagens apagadas" },
  { id: "white-046", text: "uma desculpa tão ruim que quase virou verdade" },
  { id: "white-047", text: "o tipo de festa que exige advogado no dia seguinte" },
  { id: "white-048", text: "uma autoestima importada sem garantia" },
  { id: "white-049", text: "beber água entre pecados para fingir equilíbrio" },
  { id: "white-050", text: "um flerte corporativo em planilha compartilhada" },
  { id: "white-051", text: "a nobre arte de sumir e voltar com meme" },
  { id: "white-052", text: "um perfume de rico usado para encobrir escolhas pobres" },
  { id: "white-053", text: "a frase 'confia em mim' dita por alguém inconfiante" },
  { id: "white-054", text: "o drama premium de quem não leu o combinado" },
  { id: "white-055", text: "dançar como quem foge da própria biografia" },
  { id: "white-056", text: "uma ideia péssima com ótima iluminação" },
  { id: "white-057", text: "a elegância duvidosa de chegar tarde demais" },
  { id: "white-058", text: "um print guardado para fins acadêmicos" },
  { id: "white-059", text: "a energia de vilã que paga boleto em dia" },
  { id: "white-060", text: "prometer discrição vestindo lantejoula" }
];
